server.port=8087
spring.application.name=notification-service

spring.cloud.config.enabled=false
spring.cloud.config.import-check.enabled=false

spring.datasource.url=jdbc:mysql://mysql.infra.svc.cluster.local:3306/notificationdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

eureka.client.service-url.defaultZone=http://eureka-server.infra.svc.cluster.local:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tarek.gadhgadhi@edu.isetcom.tn
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always