# ================= SERVER =================
server.port=8084
spring.application.name=api-gateway

# ================= EUREKA =================
eureka.client.service-url.defaultZone=http://eureka-server.infra.svc.cluster.local:8761/eureka/
eureka.instance.prefer-ip-address=true

# ================= GATEWAY ROUTES =================

# -------- AUTH SERVICE --------
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://auth-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**

# -------- PIPELINE SERVICE (EXISTING) --------
spring.cloud.gateway.server.webflux.routes[1].id=pipeline-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://pipeline-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/pipeline/**

# -------- SECURITY SERVICE --------
spring.cloud.gateway.server.webflux.routes[2].id=security-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://security-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/security/**

# -------- TEST ROUTE --------
spring.cloud.gateway.server.webflux.routes[3].id=test
spring.cloud.gateway.server.webflux.routes[3].uri=https://httpbin.org
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/test/**

# -------- NOTIFICATION SERVICE --------
spring.cloud.gateway.server.webflux.routes[4].id=notification-service
spring.cloud.gateway.server.webflux.routes[4].uri=lb://notification-service
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/notifications/**

# ================= CORS =================
spring.cloud.gateway.server.webflux.globalcors.add-to-simple-url-handler-mapping=true
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:4200
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowCredentials=true
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].maxAge=3600

# ================= DEBUG =================
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.cloud.loadbalancer=DEBUG

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always