# ================= SERVER =================
server.port=8085
spring.application.name=audit-log-service

# ================= EUREKA =================
eureka.client.service-url.defaultZone=http://eureka-server.infra.svc.cluster.local:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}

# ================= DATABASE =================
spring.datasource.url=jdbc:mysql://mysql.infra.svc.cluster.local:3306/auditlogdb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ================= JPA =================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ================= JWT (must match auth-service) =================
jwt.secret=stb-devsecops-platform-jwt-secret-key-2026-minimum-64-characters-required!!

# ================= ACTUATOR =================
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.health.readinessstate.enabled=true
management.health.livenessstate.enabled=true
management.metrics.tags.application=${spring.application.name}
